return {
	"preservim/nerdtree",
	"Xuyuanp/nerdtree-git-plugin",
	"SirVer/UltiSnips",
	"tpope/vim-surround",
	"vim-airline/vim-airline",
	"vim-airline/vim-airline-themes",
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		config = function()
			local configs = require("nvim-treesitter.configs")

			configs.setup({
				-- ensure_installed = { "c", "vim", "ada", "html", "python" },
				sync_install = false,
				highlight = { enable = true },
				indent = { enable = true },
			})
		end,
	},
	"f-person/git-blame.nvim",
	"p00f/nvim-ts-rainbow",
	"cohama/lexima.vim",
	"ryanoasis/vim-devicons",
	{
		"nvim-telescope/telescope.nvim",
		tag = "0.1.5",
		dependencies = { "nvim-lua/plenary.nvim" },
	},
	"fhill2/telescope-ultisnips.nvim",
	"hiroakis/cyberspace.vim",
	"tpope/vim-speeddating",
	"yannickreiss/nvim-doxyscan",
	"nvim-tree/nvim-web-devicons",
	{ "romgrk/barbar.nvim", wants = "nvim-web-devicons" },
	{ "lukas-reineke/indent-blankline.nvim", main = "ibl", opts = {} },
	"dstein64/vim-startuptime",
	"folke/tokyonight.nvim",
	"patstockwell/vim-monokai-tasty",
	"hrsh7th/nvim-cmp",
	"hrsh7th/cmp-nvim-lsp",
	"hrsh7th/cmp-nvim-lua",
	"hrsh7th/cmp-nvim-lsp-signature-help",
	"hrsh7th/cmp-path",
	"hrsh7th/cmp-buffer",
	"hrsh7th/cmp-calc",
	"hrsh7th/cmp-cmdline",
	"dmitmel/cmp-cmdline-history",
	"amarakon/nvim-cmp-lua-latex-symbols",
	{ "petertriho/cmp-git", requires = "nvim-lua/plenary.nvim" },
	"williamboman/mason.nvim",
	"williamboman/mason-lspconfig.nvim",
	"neovim/nvim-lspconfig",
	"mfussenegger/nvim-dap",
	"mhartington/formatter.nvim",
}
